### ISSUE TITLE
Ultimate can't be downloaded

### ISSUE THREAD

**Issue by hannesa2** [kurron/docker-intellij#6]
I've no ultimate license, so I run into this

> Step 6/8 : ADD https://download.jetbrains.com/idea/ideaIU-2017.2.1.tar.gz /opt/
> ADD failed: failed to GET https://download.jetbrains.com/idea/ideaIU-2017.2.1.tar.gz with status 403 Forbidden: <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5F25374F62287B85</RequestId><HostId>/X27GQfUt4qNJwgahKtunGAkoHWTOw55mrqE+coo+Xtj/e8rzl28HmV9T3DZrUzZlX/wOMGxrj8=</HostId></Error>

**Comment by hannesa2** [comment]
But it's a nice idea to have a ultimate Docker image

**Comment by kurron** [comment]
I just updated the files to use IDEA 2017.3.4 and things work for me.  If you don't want to build things yourself, I just pushed kurron/docker-intellij:latest.
